name: Alerta

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar Hola Mundo
        run: node index.js

      - name: Enviar notificacion a ntfy
        run: curl -d "Se ha realizado un nuevo push en la rama main." -H "Title: Integracion Continua ITLA" https://ntfy.sh/devops-itla